# Generated by Django 2.2.2 on 2021-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marks',
            field=models.IntegerField(default='0'),
        ),
    ]
